Symlink logs directory to openHAB share (#5)
* Copy and link logs directory

* Remove logs dir before backup

* Sort conditions ...

diff --git a/SynoPackage/scripts/postinst b/SynoPackage/scripts/postinst
--- a/SynoPackage/scripts/postinst
+++ b/SynoPackage/scripts/postinst
@@ -38,9 +38,9 @@ then
     ${BIN_SYNOSHARE} --add "${PACKAGE_NAME}" "" "${openhab_synoshare}" "" "" "" 0 0
     if [ $? -ne 0 ]
     then
-  logger -p 0 "${PACKAGE_NAME}: failed to create ${PACKAGE_NAME} share"
-  exit 1
- fi
+        logger -p 0 "${PACKAGE_NAME}: failed to create ${PACKAGE_NAME} share"
+        exit 1
+    fi
 fi
 
 # Add permissions
@@ -67,6 +67,16 @@ else
 fi
 
 ${BIN_LN} -sf  ${openhab_synoshare}/conf ${PACKAGE_TARGET_LOCATION}/src/conf
+
+# Copy and link logs directory
+if [ -d ${openhab_synoshare}/logs ]
+then
+    ${BIN_RM} -rf ${PACKAGE_TARGET_LOCATION}/src/userdata/logs
+else
+    ${BIN_MV} ${PACKAGE_TARGET_LOCATION}/src/userdata/logs ${openhab_synoshare}/
+fi
+
+${BIN_LN} -sf  ${openhab_synoshare}/logs ${PACKAGE_TARGET_LOCATION}/src/userdata/logs
 
 # Set openHAB environment from package-wizard
 if [ "${SYNOPKG_PKG_STATUS}" == "INSTALL" ]
